### ISSUE TITLE
Logo Design: Circle Blast

### ISSUE THREAD

**Issue by baranpirincal** [agneng/circle-blast#16]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by agneng** [comment]
@baranpirincal hey , thanks for your interest :-) but unfortunately i have a friend that handles this stuff , again thank you so much :-)
